const EndpointTypeActionTypes = {
    GET_LIST_ENDPOINT_TYPES: 'GET_LIST_ENDPOINT_TYPES',
    GET_ENDPOINT_TYPE: 'GET_ENDPOINT_TYPE',
    CREATE_ENDPOINT_TYPE: 'CREATE_ENDPOINT_TYPE',
    EDIT_ENDPOINT_TYPE: 'EDIT_ENDPOINT_TYPE',
    REMOVE_ENDPOINT_TYPE: 'REMOVE_ENDPOINT_TYPE'
};
export default EndpointTypeActionTypes;