const EndpointActionTypes = {
    GET_LIST_ENDPOINTS: 'GET_LIST_ENDPOINTS',
    GET_ENDPOINT: 'GET_ENDPOINT',
    CREATE_ENDPOINT: 'CREATE_ENDPOINT',
    EDIT_ENDPOINT: 'EDIT_ENDPOINT',
    REMOVE_ENDPOINT: 'REMOVE_ENDPOINT'
}
export default EndpointActionTypes;