const DashboardActionTypes = {
    GET_LIST_DASHBOARDS: 'GET_LIST_DASHBOARDS',
    GET_DASHBOARD: 'GET_LIST_DASHBOARD',
    CREATE_DASHBOARD: 'CREATE_DASHBOARD',
    EDIT_DASHBOARD: 'EDIT_DASHBOARD',
    REMOVE_DASHBOARD: 'REMOVE_DASHBOARD',
    GET_LIST_CHARTMODELS: 'GET_LIST_CHARTMODELS',
    CREATE_CHART_MODEL: 'CREATE_CHART_MODEL',
    UPDATE_CHART_MODEL: 'UPDATE_CHART_MODEL',
    DELETE_CHART_MODEL: 'DELETE_CHART_MODEL',
}
export default DashboardActionTypes;