const DeviceTypeActionTypes = {
    GET_LIST_DEVICE_TYPES: 'GET_LIST_DEVICE_TYPES',
    GET_DEVICE_TYPE: 'GET_DEVICE_TYPE',
    CREATE_DEVICE_TYPE: 'CREATE_DEVICE_TYPE',
    EDIT_DEVICE_TYPE: 'EDIT_DEVICE_TYPE',
    REMOVE_DEVICE_TYPE: 'REMOVE_DEVICE_TYPE'
};
export default DeviceTypeActionTypes;